# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CodeCov CI with Maven

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-unit-tests:

    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@main
        with:
          submodules: recursive
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Run Unit tests with Maven
        run: mvn -B clean test jacoco:report --file pom.xml --no-transfer-progress

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ./target/coverage-reports/
          fail_ci_if_error: true
          files: report
          flags: unittests
          name: codecov-umbrella
          path_to_write_report: ${basedir}/target/coverage-reports/codecov_report.txt
          verbose: true
